var Student = Backbone.Model.extend({
	defaults: {
		firstName: "",
		lastName: "",
		dateOfBirth: "",
		addressOne: "",
		addressTwo: "",
		city: "",
		stateOrProvince: "",
		country: "",
		zipCode: "",
		phoneNumber: "",
		email: "",
		allergies: "",
		previousSchools: "",
		parentFirstName: "",
		parentLastName: "",
		parentPhoneNumber: "",
		parentEmail: "",
		emergencyFirstName: "",
		emergencyLastName: "",
		emergencyRelation: "",
		emergencyPhoneNumber: ""
	},
    urlRoot: "/api/students",
});