var Student = Backbone.Model.extend({
	defaults: {
		datefyouOBirth: "",
		gender: "",
		streetAddr1: "",
		streetAddr2: "",
		city: "",
		province: "",
		country: "",
		postalCode: "",
		phoneNumber: "",
		emailAddr: "",
		allergies: "",
		prevAttendedGS: "",
		parentFirstName: "",
		parentLastName: "",
		parentPhone: "",
		parentEmailAddr: "",
		emergencyContactFirstName: "",
		emergencyContactLastName: "",
		emergencyContactRelation: "",
		emergencyContactPhoneNumber: "",
	},
    urlRoot: "http://gobind-sarvar.rhcloud.com/api/students",
});